version: 0.1
phases:
install:
commands:
- aws cloudformation package --template-file template.yaml --s3-bucket mondaymaji --output-template-file outputtemplate.yaml
artifacts:
type: zip
files:
- template.yaml
- outputtemplate.yaml